version: '3.8'

services:

  oracledb:
    image: gvenzl/oracle-xe
    container_name: oracledb
    restart: always
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./sql:/container-entrypoint-initdb.d
    networks:
      - locamail-api-network

    environment:
      - ORACLE_PASSWORD=171204
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 5s
      timeout: 5s
      retries: 50

  locamailapi:
    image: ferrarezzodev/locamailapi:latest
    container_name: locamailapi
    restart: always
    ports:
      - "80:80"
    networks:
      - locamail-api-network
    depends_on:
      oracledb:
        condition: service_healthy
     
networks:
  locamail-api-network:

volumes:
  oracle_data:
    driver: local
